import type { Metadata } from "next";
import SideLayout from "./ui/SideLayout/SideLayout";
import Header from "./ui/Header/header";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "eyero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body>
        <div className="perm">
        <SideLayout />
        <Header />
        </div>

        {children}
      </body>
    </html>
  );
}
